SaffronCity_MrPsychicsHouse_Text_YouWantedThese::
	.string "…Wait! Don't say a word!\p"
	.string "You wanted these!$"

@ Texto ajustado para citar os dois itens
SaffronCity_MrPsychicsHouse_Text_ReceivedItemsFromMrPsychic::
	.string "{PLAYER} received TM29 and a\n"
	.string "TWISTED SPOON from MR. PSYCHIC.$"

SaffronCity_MrPsychicsHouse_Text_ExplainBoth::
	.string "You already know, don't you?\n"
	.string "TM29 is PSYCHIC.\p"
	.string "And that TWISTED SPOON will boost\n"
	.string "the power of PSYCHIC moves.\p"
	.string "They are perfect together!$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
	.string "Where do you plan to put this?\n"
	.string "You've no room.$"
