Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .string "I'm on a relaxing ride on my new\n"
    .string "bike with my girlfriend.$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .string "We're going riding together on our\n"
    .string "new bikes.$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It's the Celadon Dept. Store!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There's a long path over water far\n"
    .string "away.$"

Route16_NorthEntrance_2F_Text_GiveEvioliteIfCaught20Mons::
    .string "Oh… {PLAYER}!\n"
    .string "I've been looking for you!\p"
    .string "It's me, one of the ever-present\n"
    .string "Aides to Prof. Oak.\p"
    .string "I'm supposed to give you a gift.\p"
    .string "Prof. Oak entrusted me with this\n"
    .string "Eviolite.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Do you want the Eviolite?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .string "Congratulations! Here you go!$"

Route16_NorthEntrance_2F_Text_ReceivedEvioliteFromAide::
    .string "{PLAYER} received the Eviolite\n"
    .string "from the Aide.$"

Route16_NorthEntrance_2F_Text_ExplainEviolite::
    .string "Making Pokémon evolve certainly\n"
    .string "can add to the Pokédex.\p"
    .string "However, at times, you may not\n"
    .string "want a Pokémon to evolve.\p"
    .string "In that case, give the Eviolite\n"
    .string "to that Pokémon.\p"
    .string "As long as it can still evolve,\n"
    .string "it keeps the Pokémon resilient.\p"
    .string "Its evolution is also held back,\n"
    .string "according to the Professor.$"
