ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
    .string "Hey, there!\n"
    .string "How's it going?\p"
    .string "What am I doing here, you ask?\n"
    .string "Why, I'm prospecting for gold!\p"
    .string "When I strike it rich, I'm buying\n"
    .string "a house in Kanto.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
    .string "Hey, there! How's it going?\n"
    .string "Did you hear? I've struck gold!\p"
    .string "You remembered that I was\n"
    .string "prospecting, didn't you?\p"
    .string "I've found this amidst the\n"
    .string "debris.\p"
    .string "You can't imagine just how\n"
    .string "happy I am!\p"
    .string "So I'll share my luck.\n"
    .string "This is for you!$"

ThreeIsland_DunsparceTunnel_Text_ThatsATerrainExtender::
    .string "That's a Terrain Extender!\p"
    .string "This is the sort of gift that only\n"
    .string "a rich man can give!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .string "Whoops, your Bag is crammed full!\n"
    .string "I'll give this to you later.$"

