VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "I'm getting my Pidgey to fly a\n"
    .string "letter to Saffron in the north.$"

VermilionCity_House3_Text_Pidgey::
    .string "Pidgey: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Dear Pippi,\n"
    .string "I hope to see you soon.\p"
    .string "I heard Saffron has problems with\n"
    .string "Team Rocket.\p"
    .string "Vermilion appears to be safe.$"

VermilionCity_House3_Text_BoyGiveFlightTicket::
	.string "I love Vermilion City!\n"
	.string "I want to stay here longer.\p"
	.string "I got this Flight Ticket, but\n"
	.string "I won't be needing it.\p"
	.string "Here, you can have it!$"

VermilionCity_House3_Text_BoyAlreadyGave::
	.string "Take good care of that ticket!\n"
	.string "Fly all over Kanto for me.$"
