VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "I'm getting my Pidgey to fly a\n"
    .string "letter to Saffron in the north.$"

VermilionCity_House3_Text_Pidgey::
    .string "Pidgey: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Dear Pippi,\n"
    .string "I hope to see you soon.\p"
    .string "I heard Saffron has problems with\n"
    .string "Team Rocket.\p"
    .string "Vermilion appears to be safe.$"

VermilionCity_House3_Text_BoyGiveFlightTicket::
	.string "I love Vermilion City! I want to stay\n"
	.string "here longer.\p"
	.string "I got this Flight Ticket, but I won't\n"
	.string "be needing it.\p"
	.string "Here, you can have it!$"

VermilionCity_House3_Text_BoyAlreadyGave::
	.string "Take good care of that ticket! Fly\n"
	.string "all over Kanto for me.$"
