VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "I'm getting my Pidgey to fly a\n"
    .string "letter to Saffron in the north.$"

VermilionCity_House3_Text_Pidgey::
    .string "Pidgey: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Dear Pippi,\n"
    .string "I hope to see you soon.\p"
    .string "I heard Saffron has problems with\n"
    .string "Team Rocket.\p"
    .string "Vermilion appears to be safe.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
	.string "My Pidgey usually flies me around,\n"
	.string "but we got caught in a bad storm.\p"
	.string "We stopped at a Pokémon Center\n"
	.string "and the Nurse said he needs rest.\p"
	.string "Guess I'm stuck here for a while.$"
