Route19_Text_RichardIntro::
    .string "I have to exercise and warm up\n"
    .string "before going out for a swim.$"

Route19_Text_RichardDefeat::
    .string "All warmed up!$"

Route19_Text_RichardPostBattle::
    .string "Thanks, kid!\n"
    .string "I'm ready for a swim.$"

Route19_Text_ReeceIntro::
    .string "Wait! Slow down!\n"
    .string "You'll have a heart attack!$"

Route19_Text_ReeceDefeat::
    .string "Ooh!\n"
    .string "That's chilly!$"

Route19_Text_ReecePostBattle::
    .string "Watch out for Tentacool.\n"
    .string "They sting so painfully.$"

Route19_Text_MatthewIntro::
    .string "I love swimming!\n"
    .string "What about you?$"

Route19_Text_MatthewDefeat::
    .string "Belly flop!$"

Route19_Text_MatthewPostBattle::
    .string "I can beat even marine Pokémon\n"
    .string "at swimming.$"

Route19_Text_DouglasIntro::
    .string "What's beyond the horizon?$"

Route19_Text_DouglasDefeat::
    .string "Glub!$"

Route19_Text_DouglasPostBattle::
    .string "I see a couple of islands over\n"
    .string "yonder!$"

Route19_Text_DavidIntro::
    .string "I tried diving for Pokémon, but it\n"
    .string "was a no-go.$"

Route19_Text_DavidDefeat::
    .string "Help!$"

Route19_Text_DavidPostBattle::
    .string "I guess you have to fish for sea\n"
    .string "Pokémon.$"

Route19_Text_TonyIntro::
    .string "I look at the sea to forget all\n"
    .string "the bad things that happened.$"

Route19_Text_TonyDefeat::
    .string "Ooh!\n"
    .string "Traumatic!$"

Route19_Text_TonyPostBattle::
    .string "I'm looking at the sea to forget\n"
    .string "the bad thing that happened!$"

Route19_Text_AnyaIntro::
    .string "Oh, I just love your ride!\n"
    .string "Can I have it if I win?$"

Route19_Text_AnyaDefeat::
    .string "Oh! I lost!$"

Route19_Text_AnyaPostBattle::
    .string "It's still a long way to go to\n"
    .string "Seafoam Islands…\p"
    .string "I want to go back to Fuchsia…$"

Route19_Text_AliceIntro::
    .string "Swimming's great!\n"
    .string "Sunburns aren't!$"

Route19_Text_AliceDefeat::
    .string "Shocker!$"

Route19_Text_AlicePostBattle::
    .string "My boyfriend wanted to swim to\n"
    .string "Seafoam Islands.$"

Route19_Text_AxleIntro::
    .string "Ahoy, there!\n"
    .string "These waters are treacherous!$"

Route19_Text_AxleDefeat::
    .string "Ooh!\n"
    .string "Dangerous!$"

Route19_Text_AxlePostBattle::
    .string "M-my legs! They cramped up!\n"
    .string "Glub, glub…$"

Route19_Text_ConnieIntro::
    .string "I swam here with my friends…\n"
    .string "I'm tired…$"

Route19_Text_ConnieDefeat::
    .string "I'm exhausted…$"

Route19_Text_ConniePostBattle::
    .string "If I were to ride a Pokémon on\n"
    .string "the sea, I'd like a Lapras.\p"
    .string "Lapras is so big, I bet it\n"
    .string "would keep me dry on water.$"

Route19_Text_RouteSign::
    .string "Sea Route 19\n"
    .string "Fuchsia City - Seafoam Islands$"

Route19_Text_LiaIntro::
    .string "Lia: I'm looking after my brother.\n"
    .string "He just became a Trainer.$"

Route19_Text_LiaDefeat::
    .string "Lia: That's no way to treat my\n"
    .string "little brother!$"

Route19_Text_LiaPostBattle::
    .string "Lia: Do you have a younger\n"
    .string "brother?\p"
    .string "I hope you're teaching him all\n"
    .string "sorts of things.$"

Route19_Text_LiaNotEnoughMons::
    .string "Lia: I want to battle together\n"
    .string "with my little brother.\p"
    .string "Don't you have two Pokémon?$"

Route19_Text_LucIntro::
    .string "Luc: My big sis taught me how\n"
    .string "to swim and train Pokémon.$"

Route19_Text_LucDefeat::
    .string "Luc: Oh, wow!\n"
    .string "Someone tougher than my big sis!$"

Route19_Text_LucPostBattle::
    .string "Luc: My big sis is strong and nice.\n"
    .string "I think she's awesome!$"

Route19_Text_LucNotEnoughMons::
    .string "Luc: I don't want to if I can't\n"
    .string "battle you with my big sis.\p"
    .string "Don't you have two Pokémon?$"

Route19_Text_RubberBoatGate::
	.string "Oh, a little trainer! You want to go\n"
	.string "sailing around all on your own?\p"
	.string "Hmm… you don't look quite ready to\n"
	.string "handle the open water yet.\p"
	.string "Come back when you've proven you can\n"
	.string "hold your own. Try the Gym here!$"

Route19_Text_RubberBoatOffer::
    .string "Well now! You've beaten Koga!\p"
    .string "You've proven you can handle\n"
    .string "yourself.\p"
    .string "You see, I used to be so terrified of\n"
    .string "swimming that I always carried this.\p"
    .string "It's a rubber boat! You just puff it\n"
    .string "up with air and off you go.\p"
    .string "I've finally learned how to swim on\n"
    .string "my own and I won't need it anymore.$"

Route19_Text_RubberBoatFarewell::
	.string "Just inflate it when you reach the\n"
	.string "water, and you can navigate anywhere.\p"
	.string "Isn't it wonderful? Go on and see the\n"
	.string "sea for yourself. Safe travels!$"

Route19_Text_RubberBoatPostGift::
	.string "How's the rubber boat treating you?\p"
	.string "The water's nothing to fear once you\n"
	.string "know you'll always stay afloat.$"
