CeruleanCity_House5_Text_Greeting::
	.string "Ah, a visitor! Welcome, child.\p"
	.string "I used to make all my medicines\n"
	.string "from Berry Powder, you know.\l"
	.string "Friends crushing Berries together\l"
	.string "- those were wonderful times.\p"
	.string "But nobody has the time for that\n"
	.string "sort of gathering anymore.\p"
	.string "So I kept at it and found my own\n"
	.string "new way to brew these herbs!\p"
	.string "I also sell some Berries that\n"
	.string "most folk don't give a second\l"
	.string "glance. Perhaps you'll find a\l"
	.string "use for them?$"

CeruleanCity_House5_Text_ShortGreeting::
	.string "Herbs and Berries, fresh as ever.\n"
	.string "Take your pick, young one!$"
