SilphCo_2F_Text_ConnorIntro::
    .string "Help!\n"
    .string "I'm a Silph employee.$"

SilphCo_2F_Text_ConnorDefeat::
    .string "How did you know\n"
    .string "I was a Rocket?$"

SilphCo_2F_Text_ConnorPostBattle::
    .string "I work for both Silph and TEAM\n"
    .string "Rocket.$"

SilphCo_2F_Text_JerryIntro::
    .string "It's off-limits here!\n"
    .string "Go home!$"

SilphCo_2F_Text_JerryDefeat::
    .string "You're good.$"

SilphCo_2F_Text_JerryPostBattle::
    .string "Can you solve the maze in here?\n"
    .string "It's not easy, I tell you!$"

SilphCo_2F_Text_Grunt1Intro::
    .string "No kids are allowed in here!$"

SilphCo_2F_Text_Grunt1Defeat::
    .string "Tough!$"

SilphCo_2F_Text_Grunt1PostBattle::
    .string "Diamond-shaped tiles are teleport\n"
    .string "blocks.\p"
    .string "They're transporters for this\n"
    .string "high-tech building.$"

SilphCo_2F_Text_Grunt2Intro::
    .string "Hey, kid!\n"
    .string "What are you wandering here for?$"

SilphCo_2F_Text_Grunt2Defeat::
    .string "I goofed!$"

SilphCo_2F_Text_Grunt2PostBattle::
    .string "Silph Co. will be associated with\n"
    .string "Team Rocket!$"

Text_WeatherBallTeach::
    .string "Eeek!\n"
    .string "No! Stop! Help!\p"
    .string "Oh, you're not with Team Rocket.\n"
    .string "I'm sorry, I thought…\p"
    .string "Take this Weather Ball Technical\n"
    .string "Machine as my sincere apology.$"

Text_WeatherBallTaught::
    .string "Weather Ball's type changes\n"
    .string "in different weather.\p"
    .string "It may be useful to surprise\n"
    .string "an enemy in battle.$"

SilphCo_2F_Text_FloorSign::
    .string "Silph Co. Head Office\n"
    .string "2F$"

