VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
	.string "I'm the Fishing Guru!\p"
	.string "I simply looove fishing! I can't bear\n"
	.string "to go without.\p"
	.string "Tell me, do you like to fish?$"

VermilionCity_House1_Text_TakeThisAndFish::
	.string "Grand! I like your style. I think we\n"
	.string "can be friends.\p"
	.string "Take this and fish, young friend!$"

VermilionCity_House1_Text_AlreadyHaveRodTakeMyBait::
	.string "Ah, one of my brothers already gave\n"
	.string "you a Fishing Rod!\p"
	.string "Then let me offer you my specialty:\n"
	.string "my Old Bait.$"

VermilionCity_House1_Text_BaitExplanation::
	.string "Here is the secret, my friend.\p"
	.string "That rod can hold up to three kinds\n"
	.string "of bait.\p"
	.string "Each one tempts a different sort of\n"
	.string "Pokémon from the water.\p"
	.string "Change the bait on your rod, and\n"
	.string "you'll change what you reel in!$"

VermilionCity_House1_Text_OldBaitFlavor::
	.string "My Old Bait tempts the humble sort,\n"
	.string "like Magikarp and Tentacool.\p"
	.string "Every angler starts here, my friend!$"

VermilionCity_House1_Text_SeekMyBrothers::
	.string "You now carry my Old Bait.\p"
	.string "Seek out my brothers if you wish to\n"
	.string "gather the other kinds!$"

VermilionCity_House1_Text_BaitKitComplete::
	.string "Why, you've gathered every last kind\n"
	.string "of bait there is!\p"
	.string "Your fishing kit is complete, my\n"
	.string "friend. I am so proud!$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
	.string "Oh…\n"
	.string "That's so disappointing…$"

VermilionCity_House1_Text_HowAreTheFishBiting::
	.string "Hello there, {PLAYER}! How are the\n"
	.string "fish biting?$"
