CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .string "Eevee can evolve into one of eight\n"
    .string "kinds of Pokémon.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "There's an e-mail message.\p"
    .string "… … …\p"
    .string "There are three legendary bird\n"
    .string "Pokémon.\p"
    .string "They are Articuno, Zapdos, and\n"
    .string "Moltres.\p"
    .string "Their whereabouts are unknown.\p"
    .string "We plan to explore the cavern\n"
    .string "close to Cerulean.\p"
    .string "From: Pokémon Research Team…$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "An amber pipe!$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_WelcomeEggMoveTeacher::
    .string "Ah, a visitor! I'm a Pokémon genetics\n"
    .string "researcher.\p"
    .string "My specialty is Egg Moves, traits a\n"
    .string "Pokémon can inherit at birth.\p"
    .string "For ¥10,000 to fund my work, I'll\n"
    .string "teach one to your Pokémon.\p"
    .string "Care to give it a try?$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_ReturningPlayer::
    .string "Ah, welcome back!\n"
    .string "Still interested in Egg Moves?\p"
    .string "¥10,000 and I'll teach one to your\n"
    .string "Pokémon.\p"
    .string "Shall we?$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_ChoosePokemon::
    .string "Which Pokémon should I check?$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_ComeBackAnytime::
    .string "Come back if you change your mind.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_FarewellAfterService::
    .string "Come back any time. I'll put your\n"
    .string "donation to good use!$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_NotEnoughMoney::
    .string "You don't have enough money.\n"
    .string "Come back with ¥10,000.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_CantTeachEgg::
    .string "I can't teach moves to an Egg.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_NoEggMovesToTeach::
    .string "There are no moves I can teach to\n"
    .string "that Pokémon.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_MoveTaughtSuccess::
    .string "Splendid! A fine result.\p"
    .string "Your Pokémon now knows this move as\n"
    .string "if born with it.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnotherPokemon::
	.string "Shall I teach a move to another\n"
	.string "Pokémon?$"
