LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "I once dreamt of strange items\n"
    .string "you could use in battle…\p"
    .string "X-something, they were called.\n"
    .string "Never found anything like them.$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "Did you buy some Revives?\n"
    .string "They revive any fainted Pokémon!$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "Sometimes, a Trainer duo will\n"
    .string "challenge you with two Pokémon\l"
    .string "at the same time.\p"
    .string "If that happens, you have to send\n"
    .string "out two Pokémon to battle, too.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "この　あいだ　やまおくで\n"
    .string "きんのたまを　ひろい　ましてね！\p"
    .string "つかえない　しなもの　ですが\n"
    .string "うったら　なんと　5000¥でした$"
