PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "{PLAYER} played with the NES.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It's a posted notice…\p"
    .string "If you're confused, ask for HELP!\n"
    .string "Press the L or R Button!$"

PalletTown_PlayersHouse_2F_Text_BillLetter:
    .string "There is a letter attached.\p"
    .string "“Heard you did great against the\n"
    .string "ELITE FOUR.\p"
    .string "I'm curious how you would raise\n"
    .string "these two.\p"
    .string "Take care of them and do your best!”\n"
    .string "- Bill$"

PalletTown_PlayersHouse_2F_Text_ObtainedStarter:
    .string "{PLAYER} obtained the {STR_VAR_1}!$"

PalletTown_PlayersHouse_2F_Text_TransferredToPC:
    .string "The {STR_VAR_1} was sent to\n"
    .string "Bill's PC.$"

PalletTown_PlayersHouse_2F_Text_NoRoom:
    .string "There is no more room for\n"
    .string "any more Pokémon.$"
