PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "{PLAYER} played with the Nes.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It's a posted notice…\p"
    .string "{COLOR GREEN}Enable{COLOR DARK_GRAY} or {COLOR RED}Disable{COLOR DARK_GRAY} the Level Cap\n"
    .string "by holding L and pressing Start.$"

PalletTown_PlayersHouse_2F_Text_BillLetter:
    .string "There is a letter attached.\p"
    .string "“Heard you did great against the\n"
    .string "Elite Four.\p"
    .string "I'm curious how you will raise these\n"
    .string "two.\p"
    .string "Take care of them and do your best!”\n"
    .string "- Bill$"

PalletTown_PlayersHouse_2F_Text_ObtainedStarter:
    .string "{PLAYER} obtained the {STR_VAR_1}!$"

PalletTown_PlayersHouse_2F_Text_TransferredToPC:
    .string "The {STR_VAR_1} was sent to\n"
    .string "Bill's PC.$"

PalletTown_PlayersHouse_2F_Text_NoRoom:
    .string "There is no more room for\n"
    .string "any more Pokémon.$"
