Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .string "Hi! Remember me?\n"
    .string "I'm one of Prof. Oak's AIDES.\p"
    .string "I'm supposed to give you a gift.\p"
    .string "Prof. Oak entrusted me with\n"
    .string "HM05 for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Do you want the HM05?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "Congratulations! Here you go!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "{PLAYER} received HM05\n"
    .string "from the Aide.$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "HM05 contains the hidden move\n"
    .string "FLASH.\p"
    .string "FLASH lights up even the darkest\n"
    .string "of caves and dungeons.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "Once a Pokémon learns FLASH, you\n"
    .string "can get through Rock Tunnel.$"

