Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "I run the Day-Care service.\p"
	.string "Would you like me to raise one of\n"
	.string "your Pokémon?$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "Come again.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "Which Pokémon should I raise?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "Fine.\n"
	.string "Come anytime you like.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "Fine, I'll look after your\n"
	.string "{STR_VAR_1} for a while.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "Come see me in a while.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "You're back already?\p"
	.string "Your {STR_VAR_1} needs to spend\n"
	.string "some more time with me.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "You owe me ¥{STR_VAR_2} for the return\n"
	.string "of this Pokémon.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "Thank you!\n"
	.string "Here's your Pokémon.$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER} got {STR_VAR_1} back\n"
	.string "from the Day-Care Man.$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "Oh? You only have one Pokémon\n"
	.string "with you.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "If you leave me that Pokémon,\n"
	.string "what will you battle with?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "Your {STR_VAR_1} has grown a lot.\n"
	.string "Yes, quite a lot, I'd say.\p"
	.string "Let me see…\n"
	.string "By level, it's grown by {STR_VAR_2}.\p"
	.string "Aren't I great?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "You can't take this Pokémon back\n"
	.string "if you've got no room for it.$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "You don't have enough money.$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
    .string "きみの\n"
    .string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
    .string "わるいけど　ひでんのわざを　もった\n"
    .string "ポケモンは　あずかれないなぁ$"

Text_GiveLuckyEgg_Offer::
    .string "I found this peculiar Egg, but\n"
    .string "it refuses to hatch.\p"
    .string "I've tried everything!\n"
    .string "Maybe you'll be luckier.$"

Text_GiveLuckyEgg_AfterGiving::
    .string "How's that Egg doing?\p"
    .string "Still hasn't hatched, has it?\n"
    .string "I told you it was stubborn!$"

Text_GiveLuckyEgg_BagFull::
    .string "You don't have room for it!\p"
    .string "Come back when you have space.$"
