ThreeIsland_House1_Text_YoureAlwaysSoCool::
    .string "Lostelle: Hi, {PLAYER}!\n"
    .string "You're always so cool!\p"
    .string "I'll make lunch for you, too, one\n"
    .string "day, {PLAYER}.$"

ThreeIsland_House1_Text_WeAreHavingAGoodTime::
    .string "Lostelle and I are having\n"
    .string "a wonderful time together!$"

ThreeIsland_House1_Text_RareRocksGemsDisplayed::
    .string "Rare rocks and gems are displayed.$"
