ViridianCity_Gym_Text_GiovanniIntro::
    .string "Fwahahaha! Welcome to my hideout!\p"
    .string "It shall be so until I can restore\n"
    .string "Team Rocket to its former glory.\p"
    .string "But, you have found me again. So be\n"
    .string "it.\p"
    .string "This time, I'm not holding back!\p"
    .string "Once more, you shall face Giovanni,\n"
    .string "the greatest Trainer!$"

ViridianCity_Gym_Text_RulesExplain::
    .string "However, I must maintain my facade.\p"
    .string "To keep my cover as a Gym Leader, I\n"
    .string "must abide by League rules.\p"
    .string "Three Pokémon each. A Gym Leader\n"
    .string "must play by the book, after all.\p"
    .string "{COLOR DARK_GRAY}Do you want to open the Storage\n"
    .string "System and comply with the rules?$"

ViridianCity_Gym_Text_GiovanniReady::
    .string "You have complied with the rules.\n"
    .string "Seems like you know how to obey.\p"
    .string "Now, I shall crush you with the full\n"
    .string "power of the Earth!$"

ViridianCity_Gym_Text_Refused::
    .string "Hmph. Insolent child.\p"
    .string "I cannot battle you if you do not\n"
    .string "follow the protocol.\p"
    .string "My disguise depends on it.$"

ViridianCity_Gym_Text_StillNot3::
    .string "If I cannot bend the rules, neither\n"
    .string "can you.\p"
    .string "Fix your team and do not test my\n"
    .string "patience.$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "Ha! That was a truly intense fight.$"

ViridianCity_Gym_Text_BadgeDelivery1::
    .string "Hate to admit it but… you have won.\n"
    .string "As proof, here is the Earth Badge!$"

ViridianCity_Gym_Text_BadgeDelivery2::
    .string "{COLOR DARK_GRAY}{PLAYER} received the Earth Badge\n"
    .string "from Giovanni!$"    

ViridianCity_Gym_Text_BadgeDelivery3::
    .string "The Earth Badge makes Pokémon of any\n"
    .string "level obey without question.\p"
    .string "It is evidence of your mastery as a\n"
    .string "Pokémon Trainer.\p"
    .string "With it, you can challenge the fools\n"
    .string "at the Pokémon League.$"

ViridianCity_Gym_Text_TakeThisWithYou::
    .string "Also, take this TM.\p"
    .string "Consider it a gift for your Pokémon\n"
    .string "League challenge.$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "{PLAYER} received TM26\n"
    .string "from Giovanni.$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "TM26 contains Earthquake.\p"
    .string "It is a powerful attack that causes a\n"
    .string "massive tremor.\p"
    .string "I made it when I ran the Gym here,\n"
    .string "far too long ago…$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "Having lost in this fashion, I can't\n"
    .string "face my followers.\p"
    .string "I have betrayed their trust.\p"
    .string "As of today, Team Rocket is finished\n"
    .string "forever!\p"
    .string "I have no more need for a Gym or an\n"
    .string "organization.\p"
    .string "Now nothing can distract me from my\n"
    .string "true ambition.\p"
    .string "Let us meet again someday! Farewell!$"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "You do not have space for this!$"

ViridianCity_Gym_Text_OfferPCRetrieve::
    .string "{COLOR DARK_GRAY}Do you want to access the Storage\n"
    .string "System to retrieve your team?$"

@Last line about Giovanni

ViridianCity_Gym_Text_NormanIntro::
    .string "What a mess…\p"
    .string "I was about to take up a Gym in\n"
    .string "Petalburg when I got the call.\p"
    .string "I was told to hold this post while\n"
    .string "the League figures out what to do.\p"
    .string "Anyway. The name's Norman.\p"
    .string "Acting Leader of the Viridian Gym, I\n"
    .string "suppose.\p"
    .string "I see you have the Earth Badge. So\n"
    .string "you're here for a rematch?\p"
    .string "Sorry to disappoint. Giovanni is gone.\n"
    .string "Good riddance, if you ask me.\p"
    .string "But I can accept the battle on this\n"
    .string "Gym's behalf. Good? Good.\p"
    .string "The sooner I get back home, the\n" 
    .string "better.$"

ViridianCity_Gym_Text_DoubleRulesExplain::
    .string "I don't want to mess this up, so pay\n"
    .string "attention to the rules.\p"
    .string "We'll have a Double Battle. Means two\n"
    .string "Pokémon on the field for each side.\p"
    .string "Pick four from your team and we'll\n"
    .string "get started.\p"
    .string "{COLOR DARK_GRAY}Do you want to open the Storage\n"
    .string "System to organize your party?$"

ViridianCity_Gym_Text_NormanReady::
    .string "Are you done? Great. Let's get this\n"
    .string "over with.$"

ViridianCity_Gym_Text_DoubleRefused::
    .string "Don't make me wait too long. I'd\n"
    .string "rather be home already.$"

ViridianCity_Gym_Text_StillNot4::
    .string "Is schooling in Kanto that bad? You\n"
    .string "need four Pokémon. Four.\p"
    .string "Fix it. Hurry up.$"

ViridianCity_Gym_Text_NormanDefeat::
    .string "Congratulations. That was quite a\n"
    .string "showdown.\p"
    .string "Looks like I'll enjoy my time here after\n"
    .string "all.$"

ViridianCity_Gym_Text_NoGiftNorman::
    .string "Oh. You're expecting a reward, like a\n"
    .string "TM or an item?\p"
    .string "The League doesn't allow me to give\n"
    .string "anything, sorry.\p"
    .string "We're avoiding anything that could\n"
    .string "look like a bribe.$"

ViridianCity_Gym_Text_GiftNorman::
    .string "Oh. You're expecting a reward, like a\n"
    .string "TM or an item?\p"
    .string "Is every Trainer around here that\n"
    .string "spoiled?\p"
    .string "I'm kidding. Let me see…\p"
    .string "The League doesn't allow me to give\n"
    .string "anything.\p"
    .string "But this old junk I found lying in\n"
    .string "here can't count as a bribe, right?$"

ViridianCity_Gym_Text_ExplainMachoBrace::
    .string "That's a Macho Brace.\p"
    .string "Very useful for training, but makes\n"
    .string "your Pokémon slower.\p"
    .string "Useful under Trick Room, I suppose.$"

ViridianCity_Gym_Text_NormanPostBattle::
    .string "Well… when life gives you lemons, you\n"
    .string "make lemonade, right?\p"
    .string "I'll try to enjoy my time here.$"

ViridianCity_Gym_RematchNotEnoughPlaceholder::
    .string "$"

ViridianCity_Gym_Text_YouShouldMakeRoom::
    .string "You need to unload your Bag, kid.$"

@Last line about Norman

ViridianCity_Gym_Text_YujiIntro::
    .string "Heh!\n"
    .string "You must be running out of steam\l"
    .string "by now!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "I ran out of gas!$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "You'll need power to keep up with\n"
    .string "our Gym Leader.$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "Rrrroar!\n"
    .string "I'm working myself into a rage!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "Wargh!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "I'm still not worthy!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "Pokémon and I, we make wonderful\n"
    .string "music together!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "You are in perfect harmony!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "Do you know the identity of our\n"
    .string "Gym Leader?$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "Karate is the ultimate form of\n"
    .string "martial arts!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "Aiyah!$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "If my Pokémon were as good at\n"
    .string "karate as I…$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "The truly talented win with style.$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "I lost my grip!$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "The Leader will scold me for\n"
    .string "losing this way…$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "I'm the Karate King!\n"
    .string "Your fate rests with me!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "Ayah!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "The Pokémon League?\n"
    .string "You? Don't get cocky!$"

ViridianCity_Gym_Text_ColeIntro::
    .string "Your Pokémon will cower at the\n"
    .string "crack of my whip!$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "Yowch!\n"
    .string "Whiplash!$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "Wait!\n"
    .string "I was just careless!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "Viridian Gym was closed for a\n"
    .string "long time.\p"
    .string "But now, our Leader is back!$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "I was beaten?$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "You can go on to the Pokémon\n"
    .string "League only by defeating our Gym\l"
    .string "Leader!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "Even I don't know the Viridian\n"
    .string "Leader's identity.\p"
    .string "But one thing's certain.\n"
    .string "This will be the toughest of all\l"
    .string "the Gym Leaders.\p"
    .string "Also, I heard that the Trainers\n"
    .string "here like Ground-type Pokémon.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "Blow me away! Giovanni was the\n"
    .string "Gym Leader of Viridian?$"

ViridianCity_Gym_Text_GymStatue::
    .string "Viridian Pokémon Gym\n"
    .string "Leader: ?\p"
    .string "Winning Trainers:\n"
    .string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "Viridian Pokémon Gym\n"
    .string "Leader: Giovanni\p"
    .string "Winning Trainers:\n"
    .string "{RIVAL}, {PLAYER}$"

