FuchsiaCity_House2_Text_DoYouLikeToFish::
	.string "I'm the Fishing Guru's older brother\p"
	.string "I simply looove fishing! I can't bear\n"
	.string "to go without.\p"
	.string "Tell me, do you like to fish?$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
	.string "Grand! I like your style. I think we\n"
	.string "can be friends.\p"
	.string "Take this and fish, young friend!$"

FuchsiaCity_House2_Text_AlreadyHaveRodTakeMyBait::
	.string "Ah, one of my brothers already gave\n"
	.string "you a Fishing Rod!\p"
	.string "Then let me offer you my specialty:\n"
	.string "my Good Bait.$"

FuchsiaCity_House2_Text_BaitExplanation::
	.string "Here is the secret, my friend.\p"
	.string "That rod can hold up to three kinds\n"
	.string "of bait.\p"
	.string "Each one tempts a different sort of\n"
	.string "Pokémon from the water.\p"
	.string "Change the bait on your rod, and\n"
	.string "you'll change what you reel in!$"

FuchsiaCity_House2_Text_GoodBaitFlavor::
	.string "The plain Old Bait only tempts the\n"
	.string "likes of Magikarp, yes?\p"
	.string "But my Good Bait lures finer catches\n"
	.string "to your hook!$"

FuchsiaCity_House2_Text_SeekMyBrothers::
	.string "You now carry my Good Bait.\p"
	.string "Seek out my brothers if you wish to\n"
	.string "gather the other kinds!$"

FuchsiaCity_House2_Text_BaitKitComplete::
	.string "Why, you've gathered every last kind\n"
	.string "of bait there is!\p"
	.string "Your fishing kit is complete, my\n"
	.string "friend. I am so proud!$"

FuchsiaCity_House2_Text_OhThatsDisappointing::
	.string "Oh…\n"
	.string "That's so disappointing…$"

FuchsiaCity_House2_Text_HowAreTheFishBiting::
	.string "Hello there, {PLAYER}! How are the\n"
	.string "fish biting?$"
