IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "At the Pokémon League, you will\n"
    .string "face the Elite Four all in a row.\p"
    .string "If you lose, you have to start all\n"
    .string "over again!\p"
    .string "This is it!\n"
    .string "Go for it!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "From here on, you face the\n"
    .string "Elite Four one by one.\p"
    .string "If you win, a door opens to the\n"
    .string "next Trainer. Good luck!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "I am so sorry, but you've wasted\n"
    .string "your time coming here.\p"
    .string "Lorelei of the Elite Four is\n"
    .string "absent, you see.\p"
    .string "As a result, the Pokémon League is\n"
    .string "closed for the time being.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "Agatha's Ghost-type Pokémon are\n"
    .string "horrifically terrifying in toughness.\p"
    .string "I took my Fighting-type Pokémon\n"
    .string "and raised them to the max.\p"
    .string "I went at Agatha feeling pretty\n"
    .string "confident, but she whupped us.\p"
    .string "That old lady's also got a really\n"
    .string "short fuse, too.\p"
    .string "It doesn't take anything to get\n"
    .string "that scary lady hollering.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "Maybe becoming an Elite Four\n"
    .string "member is in the blood.\p"
    .string "From what I've heard, Lance has\n"
    .string "a cousin who's a Gym Leader\l"
    .string "somewhere far away.$"

IndigoPlateau_PokemonCenter_1F_Text_CapCandyGiverPre1::
	.string "Oh! You've got the look of someone\n"
	.string "who likes a challenge…\p"
	.string "Someone who's had a hard road and\n"
	.string "kept walking anyway.\p"
	.string "That spirit deserves a reward.$"

IndigoPlateau_PokemonCenter_1F_Text_CapCandyGiverGive::
	.string "This candy never runs out, and it will\n"
	.string "raise your Pokémon's level.\p"
	.string "But it only works for those who fight\n"
	.string "within their limits. Like you.\p"
    .string "I won't keep you any longer.\n"
    .string "Best of luck to you!$"

IndigoPlateau_PokemonCenter_1F_Text_CapCandyGiverPre2::
	.string "Hmm… no.\n"
	.string "You don't need a treat from me.\p"
    .string "You've had it easy enough.$"

IndigoPlateau_PokemonCenter_1F_Text_CapCandyGiverPostCap::
	.string "Don't give up. I know you can do it!$"

IndigoPlateau_PokemonCenter_1F_Text_CapCandyGiverPostNoCap::
	.string "Oh… so you're a quitter.\p"
	.string "A shame. That candy only sweetens\n"
	.string "those with a fighting spirit.$"

IndigoPlateau_PokemonCenter_1F_Text_CapCandyCallPlayer::
    .string "Challenger!\n"
    .string "A word, if I may.$"

IndigoPlateau_PokemonCenter_1F_Text_CapCandyGiverNoRoom::
	.string "Your pack's fit to burst!\p"
	.string "Make some room and come see me\n"
	.string "again. Your reward will be waiting.$"
