CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "That Bill!\p"
    .string "I heard that he'll do whatever it\n"
    .string "takes to get rare Pokémon.\p"
    .string "He's not above doing all sorts\n"
    .string "of things, I've heard.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "Have you heard about Bill?\p"
    .string "Everyone calls him a Poké Maniac!\p"
    .string "I think people are just jealous of\n"
    .string "Bill, though.\p"
    .string "Who wouldn't want to boast about\n"
    .string "their Pokémon?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "Bill has lots of Pokémon!\n"
    .string "He collects rare ones, too!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
	.string "I could've sworn there were stairs\n"
	.string "around here somewhere…\p"
	.string "Maybe I'm just imagining things.$"
