FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Uh…\n"
    .string "Oh, yes, I'm the Move Deleter.\p"
    .string "I can make Pokémon forget their\n"
    .string "moves.\p"
    .string "Would you like me to do that?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "Which Pokémon should forget a\n"
    .string "move?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "Which move should be forgotten?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "{STR_VAR_1} seems to know only one\n"
    .string "move…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
    .string "That move should be forgotten?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "It worked to perfection!\p"
    .string "{STR_VAR_1} has forgotten\n"
    .string "{STR_VAR_2} completely.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "Come again if there are other\n"
    .string "moves to be forgotten.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "What?\n"
    .string "No Egg should know any moves.$"

Fuchsia_House_Text_TeachMonMoveForMushroom::
    .string "I'm the Fuchsia's Move Maniac.\p"
    .string "I know every single move that\n"
    .string "Pokémon learn growing up.\p"
    .string "I'm also a mushroom maniac.\p"
    .string "Bring me two Tiny Mushroom,\n"
    .string "or one Big Mushroom.\p"
    .string "If you do that for me, I'll teach\n"
    .string "a move to one Pokémon.$"

Fuchsia_House_Text_WantMeToTeachMove::
    .string "Sniff, sniff…\n"
    .string "Hm! You smell of Mushrooms!\p"
    .string "Do you want me to teach a move\n"
    .string "to a Pokémon of yours?$"

Fuchsia_House_Text_TutorWhichMon::
    .string "Which Pokémon needs tutoring?$"

Fuchsia_House_Text_TeachWhichMove::
    .string "Which move should I teach?$"

Fuchsia_House_Text_NoMoveICanTeachThatMon::
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that Pokémon.$"

Fuchsia_House_Text_IllNeedMushroomOrTwo::
    .string "Then, I'll need a Mushroom or two.\n"
    .string "What are you going to give me?$"

Fuchsia_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} handed over two\n"
    .string "Tiny Mushrooms in exchange.$"

Fuchsia_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} handed over one\n"
    .string "Big Mushroom in exchange.$"

Fuchsia_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "If your Pokémon need to learn a\n"
    .string "move, I need a Mushroom or two.$"

Fuchsia_House_Text_CantTeachAnEgg::
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an Egg.$"

