Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
    .string "Hi! Remember me?\n"
    .string "I'm one of Prof. Oak's Aides.\p"
    .string "I'm supposed to give you a gift.\p"
    .string "Prof. Oak entrusted me with the\n"
    .string "Infinite Repel for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Do you want the Infinite Repel?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
    .string "Congratulations! Here you go!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
    .string "{PLAYER} received the Infinite Repel\n"
    .string "from the Aide.$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
    .string "Infinite Repel is a Key Item.\p"
    .string "When you activate it, you won't meet\n"
    .string "any wild Pokémon while traveling.\p"
    .string "You can turn it on or off anytime\n"
    .string "from your Bag.$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "A large, shining bird is flying\n"
    .string "toward the sea.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It looks like a small island on\n"
    .string "the horizon!$"

