CeladonCity_House1_Text_ChiefFoundFlute::
	.string "Hehehe! Ever since we found\n"
	.string "this weird flute, we've been\l"
	.string "capturing Pokémon for the\l"
	.string "Game Corner like crazy!\p"
	.string "What, kid?!\n"
	.string "Don't mess with our plans!$"

CeladonCity_House1_Text_ChiefDefeated::
	.string "Argh! You little pest!$"

CeladonCity_House1_Text_ChiefFlee::
	.string "Take the flute, then!\n"
	.string "We're getting out of here!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
	.string "Chief!\p"
	.string "We just shipped two thousand\n"
	.string "more Pokémon as slot prizes\l"
	.string "again today!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
	.string "Don't touch the poster at the Game\n"
	.string "Corner!\p"
	.string "There's no secret switch behind it!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of Diglett.", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "ぶつだん　だ‥$"
