Route12_FishingHouse_Text_DoYouLikeToFish::
	.string "I'm the Fishing Guru's younger\n"
	.string "brother.\p"
	.string "I simply looove fishing! I can't bear\n"
	.string "to go without.\p"
	.string "Tell me, do you like to fish?$"

Route12_FishingHouse_Text_TakeThisAndFish::
	.string "Grand! I like your style. I think we\n"
	.string "can be friends.\p"
	.string "Take this and fish, young friend!$"

Route12_FishingHouse_Text_AlreadyHaveRodTakeMyBait::
	.string "Ah, one of my brothers already gave\n"
	.string "you a Fishing Rod!\p"
	.string "Then let me offer you my specialty:\n"
	.string "my Super Bait.$"

Route12_FishingHouse_Text_BaitExplanation::
	.string "Here is the secret, my friend.\p"
	.string "That rod can hold up to three kinds\n"
	.string "of bait.\p"
	.string "Each one tempts a different sort of\n"
	.string "Pokémon from the water.\p"
	.string "Change the bait on your rod, and\n"
	.string "you'll change what you reel in!$"

Route12_FishingHouse_Text_SuperBaitFlavor::
	.string "My Super Bait is simply the finest.\p"
	.string "It lures the rarest denizens of the\n"
	.string "deep to your hook!$"

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe::
	.string "Fishing is a way of life! It is like\n"
	.string "the finest poetry.\p"
	.string "From the seas to rivers, go out and\n"
	.string "land the big one, my friend.\p"
	.string "Now, I have a request.\p"
	.string "If you catch a big Magikarp, I want\n"
	.string "to see it.\p"
	.string "As much as I love to fish, I also\n"
	.string "love seeing gigantic Magikarp.$"

Route12_FishingHouse_Text_SeekMyBrothers::
	.string "You now carry my Super Bait.\p"
	.string "Seek out my brothers if you wish to\n"
	.string "gather the other kinds!$"

Route12_FishingHouse_Text_BaitKitComplete::
	.string "Why, you've gathered every last kind\n"
	.string "of bait there is!\p"
	.string "Your fishing kit is complete, my\n"
	.string "friend. I am so proud!$"

Route12_FishingHouse_Text_OhThatsDisappointing::
	.string "Oh…\n"
	.string "That's so disappointing…$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp::
	.string "Hello there, {PLAYER}!\n"
	.string "Have you been fishing?\p"
	.string "Try fishing with the Super Bait in\n"
	.string "any body of water.\p"
	.string "You'll find different Pokémon in\n"
	.string "different places.\p"
	.string "Oh, and don't forget to bring me\n"
	.string "gigantic Magikarp.$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee::
	.string "Oh? {PLAYER}?\n"
	.string "Why, if it isn't a Magikarp!\p"
	.string "Allow me to see it, quick!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis::
	.string "… … …Whoa!\n"
	.string "{STR_VAR_2} inches!\p"
	.string "You have a rare appreciation for\n"
	.string "the fine, poetic aspects of fishing!\p"
	.string "You must take this.\n"
	.string "I insist!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords::
	.string "I'll look forward to seeing greater\n"
	.string "records from you!$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast::
	.string "Huh?\n"
	.string "{STR_VAR_2} inches?\p"
	.string "This is the same size as the one\n"
	.string "I saw before.$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp::
	.string "Hmm…\n"
	.string "This one is {STR_VAR_2} inches long.\p"
	.string "It doesn't measure up to the\n"
	.string "{STR_VAR_3}-inch one you brought before.$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp::
	.string "Uh… That doesn't look much like\n"
	.string "a Magikarp.$"

Route12_FishingHouse_Text_NoRoomForGift::
	.string "Oh, no!\p"
	.string "I had a gift for you, but you have\n"
	.string "no room for it.$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches::
	.string "The most gigantic Magikarp\n"
	.string "I have ever witnessed…\p"
	.string "{STR_VAR_3} inches!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort::
	.string "It's a blank chart of some sort.\p"
	.string "It has spaces for writing in\n"
	.string "records of some kind.$"
