CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
	.string "Confused by the blackboard?\n"
	.string "Don't worry about it.\p"
	.string "Sometimes even I can't follow\n"
	.string "my own genius.$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER} obtained an Eevee!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
	.string "This blackboard is covered in\n"
	.string "equations and diagrams so complex\p"
	.string "they make your head spin just\n"
	.string "by looking at them.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "It's a pamphlet on TMs.\p"
    .string "… …\p"
    .string "There are 155 TMs in all.\p"
    .string "There are also seven HMs that\n"
    .string "can also be used repeatedly.\p"
    .string "Silph Co.$"
