Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "The types of Pokémon match up\n"
    .string "differently with each other.\p"
    .string "Every type is stronger than some\n"
    .string "types and weaker than others.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "A Nugget is totally useless.\n"
    .string "So I sold it for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "I heard that ghosts haunt\n"
    .string "Lavender Town.$"

Route10_PokemonCenter_1F_Text_GiveAmuletCoinIfCaught40::
    .string "Hi! Remember me?\n"
    .string "I'm one of Prof. Oak's Aides.\p"
    .string "I'm supposed to give you a gift.\p"
    .string "Prof. Oak entrusted me with an\n"
    .string "Amulet Coin for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Do you want the Amulet Coin?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Congratulations! Here you go!$"

Route10_PokemonCenter_1F_Text_ReceivedAmuletCoinFromAide::
    .string "{PLAYER} received the Amulet Coin\n"
    .string "from the Aide.$"

Route10_PokemonCenter_1F_Text_ExplainAmuletCoin::
    .string "An Amulet Coin is an item to be\n"
    .string "held by a Pokémon.\p"
    .string "If the Pokémon appears in a winning\n"
    .string "battle, you will earn more money.$"
