Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "The types of POKéMON match up\n"
    .string "differently with each other.\p"
    .string "Every type is stronger than some\n"
    .string "types and weaker than others.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "A NUGGET is totally useless.\n"
    .string "So I sold it for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "I heard that ghosts haunt\n"
    .string "LAVENDER TOWN.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "Oh… {PLAYER}!\n"
    .string "I've been looking for you!\p"
    .string "It's me, one of the ever-present\n"
    .string "AIDES to PROF. OAK.\p"
    .string "I'm supposed to give you a gift.\p"
    .string "PROF. OAK entrusted me with this\n"
    .string "Everstone.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Do you want the Everstone?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Congratulations! Here you go!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} received the Everstone\n"
    .string "from the AIDE.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "Making POKéMON evolve certainly\n"
    .string "can add to the POKéDEX.\p"
    .string "However, at times, you may not\n"
    .string "want a certain POKéMON to evolve.\p"
    .string "In that case, give the Everstone\n"
    .string "to that POKéMON.\p"
    .string "It will prevent evolution according\n"
    .string "to the PROFESSOR.$"

