Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "The types of Pokémon match up\n"
    .string "differently with each other.\p"
    .string "Every type is stronger than some\n"
    .string "types and weaker than others.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "A Nugget is totally useless.\n"
    .string "So I sold it for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "I heard that ghosts haunt\n"
    .string "Lavender Town.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "Oh… {PLAYER}!\n"
    .string "I've been looking for you!\p"
    .string "It's me, one of the ever-present\n"
    .string "Aides to Prof. Oak.\p"
    .string "I'm supposed to give you a gift.\p"
    .string "Prof. Oak entrusted me with this\n"
    .string "Everstone.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Do you want the Everstone?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Congratulations! Here you go!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} received the Everstone\n"
    .string "from the Aide.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "Making Pokémon evolve certainly\n"
    .string "can add to the Pokédex.\p"
    .string "However, at times, you may not\n"
    .string "want a certain Pokémon to evolve.\p"
    .string "In that case, give the Everstone\n"
    .string "to that Pokémon.\p"
    .string "It will prevent evolution according\n"
    .string "to the Professor.$"

