Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "I'm supposed to give you a gift.\p"
    .string "PROF. OAK entrusted me with the\n"
    .string "{STR_VAR_2} for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Do you want the {STR_VAR_2}?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "Congratulations! Here you go!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "{PLAYER} received the {STR_VAR_2}\n"
    .string "from the AIDE.$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "There are items on the ground that\n"
    .string "may be hidden from view.\p"
    .string "Use the {STR_VAR_2} to detect any\n"
    .string "hidden items close to you.\p"
    .string "The machine is a bit limited.\n"
    .string "It can't pinpoint item locations.\p"
    .string "What it does is show the direction\n"
    .string "where the item is.\p"
    .string "Use it to get your bearings, then\n"
    .string "search the suspect area by hand.$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "A big POKéMON is asleep on a road!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "What a breathtaking view!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "To get to LAVENDER TOWN from\n"
    .string "CERULEAN CITY…\p"
    .string "ROCK TUNNEL appears to be a good\n"
    .string "route to take.$"

