DiglettsCave_SouthEntrance_Text_FoundSomethingHard::
    .string "Ouch! Watch where you're digging!\p"
    .string "A DIGLETT just dropped this hard\n"
    .string "thing right on my foot!\p"
    .string "You can have it, I don't need\n"
    .string "any bumps on my head.$"

DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel::
    .string "Well, isn't this a surprise!\n"
    .string "DIGLETT dug this long tunnel!\p"
    .string "It goes right to VIRIDIAN CITY,\n"
    .string "they tell me.$"
