DiglettsCave_SouthEntrance_Text_FoundSomethingHard::
    .string "Ouch! Watch where you're digging!\p"
    .string "A Diglett just dropped this hard\n"
    .string "thing right on my foot!\p"
    .string "You can have it, I don't need\n"
    .string "any bumps on my head.$"

DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel::
    .string "Well, isn't this a surprise!\n"
    .string "Diglett dug this long tunnel!\p"
    .string "It goes right to Viridian City,\n"
    .string "they tell me.$"
