Text_DreamEaterTeach::
    .string "Yawn!\n"
    .string "I must have dozed off in the sun.\p"
    .string "I had this weird dream about\n"
    .string "a Drowzee eating my dream.\p"
    .string "And… I found this TM\n"
    .string "about how to eat dreams…\p"
    .string "Oogh, this is too spooky!\p"
    .string "Take this away from me so\n"
    .string "I can forget about it!$"

Text_DreamEaterTaught::
    .string "…Zzz…\n"
    .string "I…can't eat…anymore…$"

ViridianCity_Text_CanCarryMonsAnywhere::
    .string "Those Poké Balls at your waist!\n"
    .string "You have Pokémon, don't you?\p"
    .string "It's great that you can carry and\n"
    .string "use Pokémon anytime, anywhere.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "This Pokémon Gym is always closed.\p"
    .string "I wonder who the Leader is?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "Viridian Gym's Leader returned!$"

ViridianCity_Text_OldManGymUnderIntervention::
    .string "Did you hear? Nasty things happened\n"
    .string "inside this Gym.\p"
    .string "Word is the Pokémon League sent in\n"
    .string "a fill-in Leader to run the place\l"
    .string "while they sort it all out.$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "You want to know about the two\n"
    .string "kinds of caterpillar Pokémon?$"

ViridianCity_Text_OhOkayThen::
    .string "Oh, okay then!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "Caterpie has no poison,\n"
    .string "but Weedle does.\p"
    .string "Watch that your Pokémon aren't\n"
    .string "stabbed by Weedle's Poison Sting.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Oh, Grandpa!\n"
    .string "Don't be so mean!\p"
    .string "I'm so sorry.\n"
    .string "He hasn't had his coffee yet.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "I go shopping in Pewter City\n"
    .string "occasionally.\p"
    .string "I have to take the winding trail in\n"
    .string "Viridian Forest when I go.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "I absolutely forbid you from\n"
    .string "going through here!\p"
    .string "This is private property!$"

ViridianCity_Text_OldManOfferTutorial::
	.string "Well, now, I've had my coffee!\p"
	.string "Say, do you know how to catch\n"
	.string "a Pokémon?\p"
	.string "Want me to show you?$"

ViridianCity_Text_OldManTutorialDeclined::
	.string "Oh? You already know your stuff.\n"
	.string "Good, good!\p"
	.string "Come talk to me if you change\n"
	.string "your mind.$"

ViridianCity_Text_ShowYouHowToCatchMons::
	.string "All right, watch closely!\p"
	.string "First, weaken the wild Pokémon\n"
	.string "in battle.\p"
	.string "Then throw a Poké Ball to catch\n"
	.string "it. Like this!$"

ViridianCity_Text_ThatWasEducational::
	.string "There! Now tell me, that was\n"
	.string "educational, was it not?$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "At first, focus on weakening the\n"
    .string "Pokémon before trying to catch it.$"

ViridianCity_Text_CitySign::
    .string "Viridian City \n"
    .string "The Eternally Green Paradise$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "Trainer Tips\p"
    .string "Catch Pokémon and expand your\n"
    .string "collection.\p"
    .string "The more you have, the easier it\n"
    .string "is to battle.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "Trainer Tips\p"
    .string "The battle moves of Pokémon are\n"
    .string "limited by their Power Points, PP.\p"
    .string "To replenish PP, rest your tired\n"
    .string "Pokémon at a Pokémon Center.$"

ViridianCity_Text_GymSign::
    .string "Viridian City Pokémon Gym$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "Viridian Gym's doors are locked…$"
