VermilionCity_Gym_Text_LtSurgeIntro::
    .string "Hey, kid! What do you think you're\n"
    .string "doing here?\p"
    .string "You won't live long in combat! Not\n"
    .string "with your puny power!\p"
    .string "I tell you, kid, electric Pokémon\n"
    .string "saved me during the war!\p"
    .string "They zapped my enemies into\n"
    .string "paralysis!\p"
    .string "The same as I'll do to you!$"

VermilionCity_Gym_Text_RulesExplain::
    .string "But listen up, rookie! This ain't a\n"
    .string "battlefield!\p"
    .string "Regulation is exactly three Pokémon.\n"
    .string "Follow it or fall out.\p"
    .string "I don't waste my time on undisciplined\n"
    .string "squads.\p"
    .string "{COLOR DARK_GRAY}Do you want to access the Storage\n"
    .string "System to organize your unit?$"

VermilionCity_Gym_Text_LtSurgeReady::
    .string "At ease!\n"
    .string "You've organized your squad.\p"
    .string "Now, prepare to feel the voltage!\n"
    .string "Ten-hut!$"

VermilionCity_Gym_Text_Refused::
    .string "Dismissed!\p"
    .string "Come back when you learn to follow\n"
    .string "orders!$"

VermilionCity_Gym_Text_StillNot3::
    .string "Maggot!\p"
    .string "You still don't have exactly three\n"
    .string "Pokémon!\p"
    .string "This is insubordination! Get out of my\n"
    .string "face!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "Now that's a shocker!$"

VermilionCity_Gym_Text_BadgeDelivery1::
    .string "You're the real deal, kid!\n"
    .string "Fine, then, take the Thunder Badge!$"

VermilionCity_Gym_Text_BadgeDelivery2::
    .string "{COLOR DARK_GRAY}{PLAYER} received the Thunder Badge\n"
    .string "from Lt. Surge!$"

VermilionCity_Gym_Text_BadgeDelivery3::
    .string "The Thunder Badge cranks up your\n"
    .string "Pokémon's Speed!\p"
    .string "It also lets your Pokémon Fly\n"
    .string "lightning-quick anytime, kid!$"

VermilionCity_Gym_Text_TakeThisWithYou::
    .string "You're special, kid! Take this$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER} received TM34\n"
    .string "from Lt. Surge.$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "TM34 contains Shock Wave!\p"
    .string "Sometimes missing is not an option!$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "You've earned my respect, soldier!\n"
    .string "A little word of advice!\p"
    .string "Electricity is sure powerful! But, it's\n"
    .string "useless against Ground-type Pokémon!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "Yo, kid, make room in your Bag!$"

VermilionCity_Gym_Text_LtSurgeRematchIntro::
    .string "At ease, Champion.\p"
    .string "A soldier salutes those above him,\n"
    .string "and you outrank me now.\p"
    .string "I hope the base is up to your\n"
    .string "standards.\p"
    .string "I've been drilling hard for the day\n"
    .string "I'd face you again.\p"
    .string "And soldier, today is D-Day.$"

VermilionCity_Gym_Text_LtSurgeRematchRules::
    .string "The League has made Double Battles\n"
    .string "the new rules of engagement.\p"
    .string "Two Pokémon on the field at once,\n"
    .string "fighting side by side.\p"
    .string "Now this is real combat! Coordinated\n"
    .string "strikes, covering fire, teamwork!\p"
    .string "So muster your best four, soldier.\n"
    .string "No reserves, no excuses.\p"
    .string "Let's see if the Champion can command\n"
    .string "a squad under fire.\p"
    .string "{COLOR DARK_GRAY}Do you want to access the Storage\n"
    .string "System to organize your unit?$"

VermilionCity_Gym_Text_LtSurgeRematchReady::
    .string "Squad locked and loaded. That's what\n"
    .string "I like to see!\p"
    .string "Ten-hut, Champion! Back into the fray\n"
    .string "one last time!$"

VermilionCity_Gym_Text_RefusedRematch::
    .string "Turning tail, Champion? I don't take\n"
    .string "kindly to deserters.\p"
    .string "Fall back and regroup. Come find me\n"
    .string "when you've got the nerve!$"

VermilionCity_Gym_Text_StillNot4::
    .string "Get your platoon in line, soldier!\n"
    .string "Four Pokémon only. Headcount!$"

VermilionCity_Gym_Text_LtSurgeRematchDefeat::
    .string "Outgunned and outmaneuvered!\p"
    .string "You didn't flinch once. The mark of a\n"
    .string "true soldier and hero!\p"
    .string "Proud to serve by your side, Champion!$"

VermilionCity_Gym_Text_LtSurgeRematchBeforeReward::
    .string "To the victor go the spoils. You've\n"
    .string "earned this.$"

VermilionCity_Gym_Text_LtSurgeRematchAfterReward::    
    .string "Commit to one strike and hit with\n"
    .string "everything you've got.\p"
    .string "No hesitation. No half measures.$"

VermilionCity_Gym_Text_LtSurgeRematchPostBattle::
    .string "The private who marched in here has\n"
    .string "come a long way, Champion.\p"
    .string "That was one helluva battle.\n"
    .string "Don't ever go soft on me!$"

VermilionCity_Gym_Text_LtSurgePostRematch::
    .string "Standing by and ready, Champion.\n"
    .string "Semper Fi!$"

VermilionCity_Gym_RematchNotEnoughPlaceholder::
    .string "$"

VermilionCity_Gym_Text_OfferPCRetrieve::
    .string "{COLOR DARK_GRAY}Do you want to access the Storage\n"
    .string "System to retrieve your team?$"

@Last line related to Lt Surge

VermilionCity_Gym_Text_TuckerIntro::
    .string "When I was in the Army, Lt. Surge\n"
    .string "was my strict CO.\p"
    .string "He was a hard taskmaster.$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "Stop!\n"
    .string "You're very good!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "It's not easy opening that door.\p"
    .string "Lt. Surge was always famous for\n"
    .string "his cautious nature in the Army.$"

VermilionCity_Gym_Text_BailyIntro::
    .string "I'm a lightweight, but I'm good\n"
    .string "with electricity!\p"
    .string "That's why I joined this Gym.$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "Fried!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "Okay, I'll talk!\p"
    .string "Lt. Surge said he hid door\n"
    .string "switches inside something.$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "This is no place for kids!\n"
    .string "Not even if you're good!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "Wow!\n"
    .string "Surprised me!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "Lt. Surge installed the traps in\n"
    .string "the Gym himself.\p"
    .string "He set up double locks everywhere.\n"
    .string "Let me give you a hint.\p"
    .string "When you open the first lock, the\n"
    .string "second lock is right next to it.$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "Lt. Surge has a nickname.\p"
    .string "People refer to him as the\n"
    .string "Lightning Soldier!\p"
    .string "He's an expert on electric\n"
    .string "Pokémon.\p"
    .string "Flying/Water-type Pokémon match\n"
    .string "poorly against the Electric type.\p"
    .string "Beware of paralysis, too.\p"
    .string "Lt. Surge is very cautious.\p"
    .string "He's locked himself in, so it won't\n"
    .string "be easy getting to him.$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "Whew!\n"
    .string "That match was electric!$"

VermilionCity_Gym_Text_GymStatue::
    .string "Vermilion Pokémon Gym\n"
    .string "Leader: Lt. Surge\p"
    .string "Winning Trainers:\n"
    .string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "Vermilion Pokémon Gym\n"
    .string "Leader: Lt. Surge\p"
    .string "Winning Trainers:\n"
    .string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "Nope!\n"
    .string "There's only trash here.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "Hey! There's a switch under the\n"
    .string "trash! Turn it on!\p"
    .string "The first electric lock opened!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "The second electric lock opened!\n"
    .string "The motorized door opened!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "Nope!\n"
    .string "There's only trash here.\p"
    .string "Hey!\n"
    .string "The electric locks were reset!$"

