CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "I heard that some evolution\n"
    .string "items can only be obtained at the\p"
    .string "Game Corner. Too bad I'm not\n"
    .string "much of a gambler.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "Thanks to Erika and the ladies\n"
    .string "from the Gym, we have access to\p"
    .string "a lot of berries and seeds\n"
    .string "here in Celadon.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Express yourself with gifts!\n"
    .string "4F: Wise Man Gifts\p"
    .string "Evolution Special!\n"
    .string "Berries and Seeds!$"
