CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "I heard that some evolution\n"
    .string "items can only be obtained at the\p"
    .string "GAME CORNER. Too bad I'm not\n"
    .string "much of a gambler.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "Thanks to ERIKA and the ladies\n"
    .string "from the GYM, we have access to\p"
    .string "a lot of berries, seeds, and\n"
    .string "herbs here in CELADON.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Express yourself with gifts!\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "Evolution Special!\n"
    .string "Berries, Herbs and Seeds!$"
