PalletTown_Text_OakDontGoOut::
    .string "Oak: Hey! Wait!\n"
    .string "Don't go out!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "Oak: It's unsafe!\n"
    .string "Wild Pokémon live in tall grass!\p"
    .string "You need your own Pokémon for\n"
    .string "your protection.\p"
    .string "I know!\n"
    .string "Here, come with me!$"

PalletTown_Text_RaisingMonsToo::
    .string "I'm raising Pokémon, too.\p"
    .string "When they get strong, they can\n"
    .string "protect me.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Technology is incredible!\p"
    .string "You can now store and recall items\n"
    .string "and Pokémon as data via PC.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "Oak Pokémon Research Lab$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}'s house$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}'s house$"

PalletTown_Text_TownSign::
    .string "Pallet Town\n"
    .string "Shades of your journey await!$"

PalletTown_Text_OakLetMeSeePokedex::
	.string "Oak: Ah, {PLAYER}!\n"
	.string "You're back, are you?\p"
	.string "You just missed Bill.\n"
	.string "He had something for you.\p"
	.string "He left it in your old room,\n"
	.string "I believe. Take a look later.\p"
	.string "For now, follow me to my lab.\n"
	.string "I have a gift as well.$"

PalletTown_Text_OakYouEnjoyingTraveling::
	.string "Oak: Ah, {PLAYER}!\n"
	.string "You seem to be enjoying traveling.\p"
	.string "Knowing you, {PLAYER}, I can easily\n"
	.string "picture you in far-off lands.\p"
	.string "Good for you, good for you.\n"
	.string "Hohoho.\p"
	.string "Oh, you just missed Bill.\n"
	.string "He had something for you.\p"
	.string "He left it in your old room,\n"
	.string "I believe. Take a look later.$"
