CeladonCity_Hotel_Text_AmuletIntro::
	.string "Oh dear! I don't know what to do.\p"
	.string "It's been so long since someone\n"
	.string "left this amulet with me…\p"
	.string "I don't think the owner will ever\n"
	.string "come back for it.\p"
	.string "This hotel doesn't accept Pokémon,\n"
	.string "but I can at least give you this.$"

CeladonCity_Hotel_Text_AmuletPost::
	.string "Don't worry, dear.\n"
	.string "It's been here far too long.\p"
	.string "Whoever left it here won't be\n"
	.string "needing it anymore.$"

CeladonCity_Hotel_Text_BagFull::
	.string "Oh my! Your bag seems to be full.\n"
	.string "Come back when you have some room.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .string "I'm on vacation with my brother and\n"
    .string "boyfriend.\p"
    .string "Celadon is such a pretty city!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
    .string "Why?\n"
    .string "Why did she bring her brother?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .string "Yippee! I'm on vacation!\n"
    .string "My sis brought me along! Awesome!$"

